name: Schedule Matrix Builds
on:
  workflow_dispatch:

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    permissions:
      actions: write  
      contents: read
      statuses: write
    steps:
      - name: Trigger Matrix Builds
        env:
          GH_TOKEN: "${{ github.token }}"
        run: |
          ##presets
          set +x ; set +e
          #-------------#        
          gh workflow run "matrix_builds.yaml" \
            --repo "${GITHUB_REPOSITORY}" \
            --ref "${GITHUB_REF}" \
            -f host="ALL" \
            -f sbuild-url="https://raw.githubusercontent.com/pkgforge/soarpkgs/refs/heads/main/binaries/zsv/static.ppkg.stable.yaml" \
            -f ghcr-url="ghcr.io/pkgforge/bincache/zsv/ppkg" \
            -f pkg-family="zsv" \
            -f debug="false" \
            -f logs="true" \
            -f rebuild="true"
        continue-on-error: false        